<?php include("header.php") ?>


<div class="row-fluid">
	<div class="span2">
		<h2>Barre de menus</h2>
		<p>
			Lorem iibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus nunc risus, pretium vel laoreet eu, fermentum ac magna. Praesent eu lacus lectus, sit amet malesuada nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam non felis purus, ut faucibus nibh. Cras ut massa erat, ac iaculis arcu. Suspendisse ac ipsum nibh, ut pharetra lectus.
		</p>
	</div>
	
	<div class="span6">
		<h1>ActualitÃÂ©s de Didapi</h1>
		
		<h2 id="actu">ActualitÃÂ© 1</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id sapien et dolor congue porta ut at dui. Fusce ut lacus tellus, vitae sodales tellus. Donec urna dolor, elementum in tincidunt eget, adipiscing eget ligula. Nulla volutpat porttitor nisi, non vehicula velit porta aliquam. Nullam bibendum leo ut quam scelerisque laoreet. Integer suscipit laoreet turpis, sit amet interdum nisi dignissim eget. Donec scelerisque elit eget arcu ultricies condimentum. Nunc dolor odio, laoreet eget elementum et, eleifend quis lacus. Proin eget lectus lorem, at dictum nisl. Quisque et augue nec massa dictum feugiat. Sed lacus sem, hendrerit eu convallis ac, lacinia vel enim.
			Donec vulputate vulputate metus, tristique posuere nulla tempor ac. Duis non justo eu leo pulvinar volutpat. Etiam vel tortor vitae risus facilisis tristique quis eu nisl. Duis quis felis dui. Fusce euismod fringilla leo non fringilla. Nam sit amet velit non massa suscipit ultrices nec at mi. Quisque elementum aliquet est sed venenatis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec imperdiet varius orci, vel consectetur eros lacinia sit amet. Duis et diam magna. Nulla congue accumsan ligula, vel rutrum velit dapibus vehicula. Aenean feugiat, neque in bibendum adipiscing, leo nulla eleifend quam, ac laoreet elit enim et turpis. Quisque vel mi non nisl elementum porta. Ut semper placerat ornare. Donec a tincidunt lectus. Proin sit amet elementum risus.
			Nullam condimentum congue tellus, at sodales nunc facilisis vitae. In gravida convallis massa, id imperdiet sem tristique in. Maecenas tortor dui, fringilla vitae pretium eu, venenatis eget velit. Mauris vel lobortis felis. Vestibulum ante nisl, elementum at venenatis ac, venenatis nec tellus. Mauris ornare pharetra est id convallis. Mauris eu libero tellus. Fusce ut turpis augue. Cras ultricies justo nec leo iaculis adipiscing. Donec lobortis urna sit amet nibh rhoncus eget vehicula magna fringilla. Aliquam venenatis viverra ante, at condimentum arcu tincidunt non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non justo ante, ac tristique risus. Nam elit nibh, vehicula quis venenatis nec, vehicula id velit.
			Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus nunc risus, pretium vel laoreet eu, fermentum ac magna. Praesent eu lacus lectus, sit amet malesuada nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam non felis purus, ut faucibus nibh. Cras ut massa erat, ac iaculis arcu. Suspendisse ac ipsum nibh, ut pharetra lectus.
			Fusce lacus dolor, egestas quis porta at, semper vel arcu. Ut viverra ultrices urna, dignissim dignissim dui egestas consequat. Sed faucibus pellentesque ipsum nec sollicitudin. Aliquam in condimentum lorem. Aliquam eget varius quam. Fusce felis libero, consectetur non viverra in, laoreet facilisis lectus. Sed id ante vel magna cursus adipiscing. Praesent congue dui erat. Donec commodo consequat orci, a eleifend nisi mollis vitae. Nunc eu leo ut massa congue iaculis sed non nunc. Nullam interdum arcu ac purus aliquet vel dapibus libero pretium. Aenean fermentum nunc dui, sit amet laoreet eros. Praesent vitae justo arcu. Proin aliquet, lacus eget euismod consequat, nulla tortor rutrum augue, eu imperdiet ligula nunc in turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
		</p>
		<h2 id="products">ActualitÃÂ© 2</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id sapien et dolor congue porta ut at dui. Fusce ut lacus tellus, vitae sodales tellus. Donec urna dolor, elementum in tincidunt eget, adipiscing eget ligula. Nulla volutpat porttitor nisi, non vehicula velit porta aliquam. Nullam bibendum leo ut quam scelerisque laoreet. Integer suscipit laoreet turpis, sit amet interdum nisi dignissim eget. Donec scelerisque elit eget arcu ultricies condimentum. Nunc dolor odio, laoreet eget elementum et, eleifend quis lacus. Proin eget lectus lorem, at dictum nisl. Quisque et augue nec massa dictum feugiat. Sed lacus sem, hendrerit eu convallis ac, lacinia vel enim.
			Donec vulputate vulputate metus, tristique posuere nulla tempor ac. Duis non justo eu leo pulvinar volutpat. Etiam vel tortor vitae risus facilisis tristique quis eu nisl. Duis quis felis dui. Fusce euismod fringilla leo non fringilla. Nam sit amet velit non massa suscipit ultrices nec at mi. Quisque elementum aliquet est sed venenatis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec imperdiet varius orci, vel consectetur eros lacinia sit amet. Duis et diam magna. Nulla congue accumsan ligula, vel rutrum velit dapibus vehicula. Aenean feugiat, neque in bibendum adipiscing, leo nulla eleifend quam, ac laoreet elit enim et turpis. Quisque vel mi non nisl elementum porta. Ut semper placerat ornare. Donec a tincidunt lectus. Proin sit amet elementum risus.
			Nullam condimentum congue tellus, at sodales nunc facilisis vitae. In gravida convallis massa, id imperdiet sem tristique in. Maecenas tortor dui, fringilla vitae pretium eu, venenatis eget velit. Mauris vel lobortis felis. Vestibulum ante nisl, elementum at venenatis ac, venenatis nec tellus. Mauris ornare pharetra est id convallis. Mauris eu libero tellus. Fusce ut turpis augue. Cras ultricies justo nec leo iaculis adipiscing. Donec lobortis urna sit amet nibh rhoncus eget vehicula magna fringilla. Aliquam venenatis viverra ante, at condimentum arcu tincidunt non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non justo ante, ac tristique risus. Nam elit nibh, vehicula quis venenatis nec, vehicula id velit.
			Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus nunc risus, pretium vel laoreet eu, fermentum ac magna. Praesent eu lacus lectus, sit amet malesuada nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam non felis purus, ut faucibus nibh. Cras ut massa erat, ac iaculis arcu. Suspendisse ac ipsum nibh, ut pharetra lectus.
			Fusce lacus dolor, egestas quis porta at, semper vel arcu. Ut viverra ultrices urna, dignissim dignissim dui egestas consequat. Sed faucibus pellentesque ipsum nec sollicitudin. Aliquam in condimentum lorem. Aliquam eget varius quam. Fusce felis libero, consectetur non viverra in, laoreet facilisis lectus. Sed id ante vel magna cursus adipiscing. Praesent congue dui erat. Donec commodo consequat orci, a eleifend nisi mollis vitae. Nunc eu leo ut massa congue iaculis sed non nunc. Nullam interdum arcu ac purus aliquet vel dapibus libero pretium. Aenean fermentum nunc dui, sit amet laoreet eros. Praesent vitae justo arcu. Proin aliquet, lacus eget euismod consequat, nulla tortor rutrum augue, eu imperdiet ligula nunc in turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
		</p>
		<h2 id="contact">ActualitÃÂ© 3</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id sapien et dolor congue porta ut at dui. Fusce ut lacus tellus, vitae sodales tellus. Donec urna dolor, elementum in tincidunt eget, adipiscing eget ligula. Nulla volutpat porttitor nisi, non vehicula velit porta aliquam. Nullam bibendum leo ut quam scelerisque laoreet. Integer suscipit laoreet turpis, sit amet interdum nisi dignissim eget. Donec scelerisque elit eget arcu ultricies condimentum. Nunc dolor odio, laoreet eget elementum et, eleifend quis lacus. Proin eget lectus lorem, at dictum nisl. Quisque et augue nec massa dictum feugiat. Sed lacus sem, hendrerit eu convallis ac, lacinia vel enim.
			Donec vulputate vulputate metus, tristique posuere nulla tempor ac. Duis non justo eu leo pulvinar volutpat. Etiam vel tortor vitae risus facilisis tristique quis eu nisl. Duis quis felis dui. Fusce euismod fringilla leo non fringilla. Nam sit amet velit non massa suscipit ultrices nec at mi. Quisque elementum aliquet est sed venenatis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec imperdiet varius orci, vel consectetur eros lacinia sit amet. Duis et diam magna. Nulla congue accumsan ligula, vel rutrum velit dapibus vehicula. Aenean feugiat, neque in bibendum adipiscing, leo nulla eleifend quam, ac laoreet elit enim et turpis. Quisque vel mi non nisl elementum porta. Ut semper placerat ornare. Donec a tincidunt lectus. Proin sit amet elementum risus.
			Nullam condimentum congue tellus, at sodales nunc facilisis vitae. In gravida convallis massa, id imperdiet sem tristique in. Maecenas tortor dui, fringilla vitae pretium eu, venenatis eget velit. Mauris vel lobortis felis. Vestibulum ante nisl, elementum at venenatis ac, venenatis nec tellus. Mauris ornare pharetra est id convallis. Mauris eu libero tellus. Fusce ut turpis augue. Cras ultricies justo nec leo iaculis adipiscing. Donec lobortis urna sit amet nibh rhoncus eget vehicula magna fringilla. Aliquam venenatis viverra ante, at condimentum arcu tincidunt non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non justo ante, ac tristique risus. Nam elit nibh, vehicula quis venenatis nec, vehicula id velit.
			Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus nunc risus, pretium vel laoreet eu, fermentum ac magna. Praesent eu lacus lectus, sit amet malesuada nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam non felis purus, ut faucibus nibh. Cras ut massa erat, ac iaculis arcu. Suspendisse ac ipsum nibh, ut pharetra lectus.
			Fusce lacus dolor, egestas quis porta at, semper vel arcu. Ut viverra ultrices urna, dignissim dignissim dui egestas consequat. Sed faucibus pellentesque ipsum nec sollicitudin. Aliquam in condimentum lorem. Aliquam eget varius quam. Fusce felis libero, consectetur non viverra in, laoreet facilisis lectus. Sed id ante vel magna cursus adipiscing. Praesent congue dui erat. Donec commodo consequat orci, a eleifend nisi mollis vitae. Nunc eu leo ut massa congue iaculis sed non nunc. Nullam interdum arcu ac purus aliquet vel dapibus libero pretium. Aenean fermentum nunc dui, sit amet laoreet eros. Praesent vitae justo arcu. Proin aliquet, lacus eget euismod consequat, nulla tortor rutrum augue, eu imperdiet ligula nunc in turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
		</p>
	</div>
	
	<div class="span4">
		<h2>Barre latÃÂ©rale</h2>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id sapien et dolor congue porta ut at dui. Fusce ut lacus tellus, vitae sodales tellus. Donec urna dolor, elementum in tincidunt eget, adipiscing eget ligula. Nulla volutpat porttitor nisi, non vehicula velit porta aliquam. Nullam bibendum leo ut quam scelerisque laoreet. Integer suscipit laoreet turpis, sit amet interdum nisi dignissim eget. Donec scelerisque elit eget arcu ultricies condimentum. Nunc dolor odio, laoreet eget elementum et, eleifend quis lacus. Proin eget lectus lorem, at dictum nisl. Quisque et augue nec massa dictum feugiat. Sed lacus sem, hendrerit eu convallis ac, lacinia vel enim.
			Donec vulputate vulputate metus, tristique posuere nulla tempor ac. Duis non justo eu leo pulvinar volutpat. Etiam vel tortor vitae risus facilisis tristique quis eu nisl. Duis quis felis dui. Fusce euismod fringilla leo non fringilla. Nam sit amet velit non massa suscipit ultrices nec at mi. Quisque elementum aliquet est sed venenatis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec imperdiet varius orci, vel consectetur eros lacinia sit amet. Duis et diam magna. Nulla congue accumsan ligula, vel rutrum velit dapibus vehicula. Aenean feugiat, neque in bibendum adipiscing, leo nulla eleifend quam, ac laoreet elit enim et turpis. Quisque vel mi non nisl elementum porta. Ut semper placerat ornare. Donec a tincidunt lectus. Proin sit amet elementum risus.
			Nullam condimentum congue tellus, at sodales nunc facilisis vitae. In gravida convallis massa, id imperdiet sem tristique in. Maecenas tortor dui, fringilla vitae pretium eu, venenatis eget velit. Mauris vel lobortis felis. Vestibulum ante nisl, elementum at venenatis ac, venenatis nec tellus. Mauris ornare pharetra est id convallis. Mauris eu libero tellus. Fusce ut turpis augue. Cras ultricies justo nec leo iaculis adipiscing. Donec lobortis urna sit amet nibh rhoncus eget vehicula magna fringilla. Aliquam venenatis viverra ante, at condimentum arcu tincidunt non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non justo ante, ac tristique risus. Nam elit nibh, vehicula quis venenatis nec, vehicula id velit.
			Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus nunc risus, pretium vel laoreet eu, fermentum ac magna. Praesent eu lacus lectus, sit amet malesuada nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam non felis purus, ut faucibus nibh. Cras ut massa erat, ac iaculis arcu. Suspendisse ac ipsum nibh, ut pharetra lectus.
			Fusce lacus dolor, egestas quis porta at, semper vel arcu. Ut viverra ultrices urna, dignissim dignissim dui egestas consequat. Sed faucibus pellentesque ipsum nec sollicitudin. Aliquam in condimentum lorem. Aliquam eget varius quam. Fusce felis libero, consectetur non viverra in, laoreet facilisis lectus. Sed id ante vel magna cursus adipiscing. Praesent congue dui erat. Donec commodo consequat orci, a eleifend nisi mollis vitae. Nunc eu leo ut massa congue iaculis sed non nunc. Nullam interdum arcu ac purus aliquet vel dapibus libero pretium. Aenean fermentum nunc dui, sit amet laoreet eros. Praesent vitae justo arcu. Proin aliquet, lacus eget euismod consequat, nulla tortor rutrum augue, eu imperdiet ligula nunc in turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
		</p>
	</div>
</div>

<?php include("footer.php") ?>